name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install secrets
        run: .github/workflows/create-secrets.sh
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
          SECRETS: ${{ secrets.SECRETS }}

      - name: Set up SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.2
      - name: Set up NDK
        run: $ANDROID_HOME/tools/bin/sdkmanager "ndk;$(grep "ndkVersion" ./gradle/versions.gradle | sed 's/.*"\(.*\)"/\1/')" --channel=3

      - id: build
        name: Build with Gradle
        run: ./gradlew ktlintCheck detekt build bundle -Dorg.gradle.caching=false
          -Pkotlin.incremental=false -Pkapt.incremental.apt=false

      - name: Store reports
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: Reports
          path: build/reports
      - name: Store outputs
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: Outputs
          path: build/outputs

      - id: calculate-commit-range
        name: Calculate commit range
        uses: actions/github-script@0.2.0
        if: success() && github.ref == 'refs/heads/master'
        with:
          github-token: ${{github.token}}
          script: |
            const query = `{
              repository(owner: "proxer", name: "ProxerAndroid") {
                ref(qualifiedName: "master") {
                  target {
                    ... on Commit {
                      history(first: 20, after: "${context.sha} 0") {
                        edges {
                          node {
                            oid
                            message
                            status {
                              state
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }`

            const result = await github.graphql(query)
            const history = result.repository.ref.target.history.edges
            const firstSuccessfulCommit = history.findIndex(it => it.node.status && it.node.status.state === "SUCCESS")

            if (firstSuccessfulCommit >= 0) {
              return `${history[firstSuccessfulCommit].node.oid}...${context.sha}`
            } else {
              return `${context.sha}~1...${context.sha}`
            }

      - name: Publish to Telegram
        if: success() && github.ref == 'refs/heads/master'
        run: .github/workflows/publish-to-telegram.sh
        env:
          COMMIT_RANGE: ${{ steps.calculate-commit-range.outputs.result }}
          TELEGRAM_BOT_ID: ${{ secrets.TELEGRAM_BOT_ID }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      # TODO: Github actions do not seem to set the commit status automatically yet. Try without later.
      - name: Set Commit Status
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{github.token}}
          script: |
            github.repos.createStatus({owner: "proxer", repo: "ProxerAndroid", sha: context.sha, state: "success"})
